#!/bin/bash
delim="|"
tempfile=`mktemp`
digresultemp=`mktemp`;
sorttemp=`mktemp`
for i in `cat ./upload/domains`;
do
        DOMAIN=`echo $i | cut -d, -f1`;
        COUNTS=`echo $i | cut -d, -f2`;
		
        dig $DOMAIN mx +short > $digresultemp;
	cat $digresultemp | sort -n > $sorttemp;
		
        echo -n "$DOMAIN" >> $tempfile;
        echo -n "$delim" >> $tempfile;
        echo -n "$COUNTS" >> $tempfile;
        echo -n "$delim" >> $tempfile;
        cat $sorttemp | awk '{printf "%s%s",$2,"|"}' | sed 's/.$//' >> $tempfile;
	echo "" >> $tempfile;
		
done;
cat $tempfile > ./upload/domains.resolved;
rm -f $tempfile $digresultemp $sorttemp;